[ENG-2383] Add Documentation For Collections
CenterForOpenScience/developer.osf.io pull request #52
Opened 2020-12-17 14:35 UTC by Johnetordoff

## Purpose

Document all the endpoints for our collections feature.

# Changes

- add files for each collections endpoint
- fixes minor repeated typos

# Side Effects 

None that I know of.

 # Ticket

https://openscience.atlassian.net/browse/ENG-2383

2020-12-17 15:45 UTC, corbinSanders commented on swagger-spec/collections/collected_metadata_list.yaml
> +  summary: Add Metadata or Subjects to a Entitiy in a Collection
Still a typo

2020-12-17 15:46 UTC, corbinSanders commented on swagger-spec/collections/collected_metadata_subjects_relationships.yaml
> +  summary: Retrieve subjuct metadata for a specific piece of metadata in a collection
Typo

2020-12-17 15:47 UTC, corbinSanders requested changes
A few typos. Otherwise looks good

2020-12-17 16:56 UTC, corbinSanders commented
LGTM

2021-01-11 21:17 UTC, jwalz approved these changes

2021-01-11 21:26 UTC, merged