[ENG-6782] Update preprint API documents
CenterForOpenScience/developer.osf.io pull request #65
Opened 2024-12-24 12:33 UTC by Ostap-Zherebetskyi

Purpose
Add versioned preprints endpoints

Changes
See diff 
Ticket
https://openscience.atlassian.net/browse/ENG-6782

2024-12-26 13:11 UTC, cslzchen approved these changes
Looks good and will close the ticket.

- [ ] Ask @brianjgeiger to take a second look when he is back
- [ ] PR will be merged after/during release

2025-01-28 16:13 UTC, brianjgeiger requested changes
Looks like the JSON from the API Responses needs updating. For the one I commented on, I'd grab https://api.osf.io/v2/preprints/hqb2p/ and just use that. For the POST response, I think you need to make sure that all of the links to the preprint include the version number in, and make sure all the links are there.

2025-01-29 13:45 UTC, Ostap-Zherebetskyi commented on swagger-spec/preprints/versioned_preprints_list.yaml
> +                preprint_doi: 'https://dx.doi.org/10.5072/FK2OSF.IO/HQB2P'
updated responses using the latest information from https://api.osf.io/v2/preprints/hqb2p/

2025-01-29 13:57 UTC, brianjgeiger approved these changes

2025-01-29 15:19 UTC, merged